# Generated by Django 5.2.1 on 2025-07-06 11:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_store_shop'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Especificacao',
            new_name='Specs',
        ),
        migrations.RenameModel(
            old_name='Shop',
            new_name='Store',
        ),
    ]
