# Generated by Django 5.2.1 on 2025-07-06 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_rename_especificacao_specs_rename_shop_store'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Specs',
            new_name='Spec',
        ),
    ]
