# Generated by Django 5.2.1 on 2025-07-06 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quantity',
            new_name='stock',
        ),
    ]
