# Generated by Django 5.2.1 on 2025-07-07 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_rename_quantity_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(default='Lichinga', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.CharField(default=844444443, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='phone2',
            field=models.CharField(default=86778884764, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='slum',
            field=models.CharField(default='Bairro Popular'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='frete',
            field=models.FloatField(default=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='store',
            name='city',
            field=models.CharField(default='Lichinga', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='store',
            name='phone2',
            field=models.CharField(default=8754576445, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='store',
            name='slum',
            field=models.CharField(default="N'zinge"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='store',
            name='phone',
            field=models.CharField(max_length=40),
        ),
    ]
