# Generated by Django 5.2.1 on 2025-07-13 20:09

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_customer_id_alter_order_id_alter_orderitem_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=cloudinary.models.CloudinaryField(default='null', max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
